### ISSUE TITLE
User stack symbols not getting resolved. 

### ISSUE THREAD

**Issue by Eric-Marnadi** [iovisor/bcc#1694] opened 2018-04-20 02:16 UTC
```
prab@x1c:~/dev$ nm test | grep send
00000000004055f1 T _Z7sendMsgv
```

here bpf driver code 

```c++
const std::string BPF_PROGRAM = R"(
#include <linux/sched.h>
#include <uapi/linux/ptrace.h>

struct stack_key_t {
  int pid;
  char name[16];
  int user_stack;
  int kernel_stack;
};

BPF_STACK_TRACE(stack_traces, 10240)
BPF_HASH(counts, struct stack_key_t, uint64_t);

int on_tcp_send(struct pt_regs *ctx) {
  struct stack_key_t key = {};
  key.pid = bpf_get_current_pid_tgid() >> 32;
  bpf_get_current_comm(&key.name, sizeof(key.name));
  key.kernel_stack = stack_traces.get_stackid(ctx, BPF_F_REUSE_STACKID);
  key.user_stack = stack_traces.get_stackid(
    ctx, BPF_F_REUSE_STACKID | BPF_F_USER_STACK
  );

  u64 zero = 0, *val;
  val = counts.lookup_or_init(&key, &zero);
  (*val)++;

  return 0;
}
)";

// Define the same struct to use in user space.
struct stack_key_t {
  int pid;
  char name[16];
  int user_stack;
  int kernel_stack;
};

int main(int argc, char** argv) {
  ebpf::BPF bpf;
  auto init_res = bpf.init(BPF_PROGRAM);
  if (init_res.code() != 0) {
    std::cerr << init_res.msg() << std::endl;
    return 1;
  }

  auto attach_res = bpf.attach_uprobe("/home/prab/dev/test", "_Z7sendMsgv", "on_tcp_send");
  if (attach_res.code() != 0) {
    std::cerr << attach_res.msg() << std::endl;
    return 1;
  }
```

when I run the bpf code the stacks are not resolved 

```
prog tag mismatch 4384fcafe3cbe063 11
Probing for 10 seconds
PID: 27221 (test) made 1 TCP sends on following stack: 
  Kernel Stack:
    -14
  User Stack:
    [UNKNOWN]
    [UNKNOWN]
    [UNKNOWN]
PID: 27217 (test) made 1 TCP sends on following stack: 
  Kernel Stack:
    -14
  User Stack:
    [UNKNOWN]
    [UNKNOWN]
    [UNKNOWN]
```

Anything missing or is this issue with the user stack not getting resolved by BPF.

**Comment by palmtenor** [comment] 2018-04-20 04:09
How were you resolving symbols? The code you posted didn’t include that part.

**Comment by Eric-Marnadi** [comment] 2018-04-20 04:36
@palmtenor  - here is the rest of the code 
  auto stacks = bpf.get_stack_table("stack_traces");


  for (auto it : table) {
    std::cout << "PID: " << it.first.pid << " (" << it.first.name << ") "
              << "made " << it.second
              << " TCP sends on following stack: " << std::endl;
    std::cout << "  Kernel Stack:" << std::endl;
    if (it.first.kernel_stack >= 0) {
      auto syms = stacks.get_stack_symbol(it.first.kernel_stack, -1);
      for (auto sym : syms)
        std::cout << "    " << sym << std::endl;
    } else
      std::cout << "    " << it.first.kernel_stack << std::endl;
    std::cout << "  User Stack:" << std::endl;
    if (it.first.user_stack >= 0) {
      auto syms = stacks.get_stack_symbol(it.first.user_stack, it.first.pid);
      for (auto sym : syms)
        std::cout << "    " << sym << std::endl;
    } else
      std::cout << "    " << it.first.user_stack << std::endl;
  }

**Comment by Eric-Marnadi** [comment] 2018-04-21 04:42
@palmtenor  - not sure if this gives any hint. The addr seems to be random I think
Here is the output
PID: 3729 (test) made 1Sends on following stack: 
  User Stack:
 Stack Id:7149
addr->4216305
addr->140020882040880
addr->10193376095400902997
    [UNKNOWN]
    [UNKNOWN]
    [UNKNOWN]

**Comment by yonghong-song** [comment] 2018-04-21 06:05
This, `prog tag mismatch 4384fcafe3cbe063 11`, is strange as well. The prog stored in bcc is different from what is stored in kernel?

**Comment by yonghong-song** [comment] 2018-04-23 06:35
Looks like you have multiple test programs are running and in the bpf program, you have BPF_F_REUSE_STACKID. Could you try to remove BPF_F_REUSE_STACKID and try again?
This can avoid the situation where key.pid and key.stack_id do not match each other (during stack_id may later be reused by a different pid).

If you still have problem, maybe you can post the source of your test program as well, so folks here can help you troubleshoot.

**Comment by Eric-Marnadi** [comment] 2018-04-26 00:40
@palmtenor @yonghong-song tried with removing the flag BPF_F_REUSE_STACKID and it did not help 

Here is the code. 

#include <unistd.h>
#include <algorithm>
#include <iostream>

#include "BPF.h"

const std::string BPF_PROGRAM = R"(
#include <linux/sched.h>
#include <uapi/linux/ptrace.h>

struct stack_key_t {
  int pid;
  char name[16];
  int user_stack;
};

BPF_STACK_TRACE(stack_traces, 10240)
BPF_HASH(counts, struct stack_key_t, uint64_t);

int on_send(struct pt_regs *ctx) {
  struct stack_key_t key = {};
  key.pid = bpf_get_current_pid_tgid() >> 32;
  bpf_get_current_comm(&key.name, sizeof(key.name));
  key.user_stack = stack_traces.get_stackid(
    ctx, BPF_F_USER_STACK
  );

  

  u64 zero = 1, *val;
  val = counts.lookup_or_init(&key, &zero);

  return 0;
}
)";

// Define the same struct to use in user space.
struct stack_key_t {
  int pid;
  char name[16];
  int user_stack;
  int kernel_stack;
};

int main(int argc, char** argv) {
  ebpf::BPF bpf;
  auto init_res = bpf.init(BPF_PROGRAM);
  if (init_res.code() != 0) {
    std::cerr << init_res.msg() << std::endl;
    return 1;
  }

  auto attach_res = bpf.attach_uprobe("/home/prab/develop/bcc/build/send", "_Z4sendv", "on_send");
  if (attach_res.code() != 0) {
    std::cerr << attach_res.msg() << std::endl;
    return 1;
  }

  int probe_time = 10;
  if (argc == 2) {
    probe_time = atoi(argv[1]);
  }
  std::cout << "Probing for " << probe_time << " seconds" << std::endl;
  sleep(probe_time);

  auto table =
      bpf.get_hash_table<stack_key_t, uint64_t>("counts").get_table_offline();
  std::sort(table.begin(), table.end(), [](std::pair<stack_key_t, uint64_t> a,
                                           std::pair<stack_key_t, uint64_t> b) {
    return a.second < b.second;
  });
  auto stacks = bpf.get_stack_table("stack_traces");

  for (auto it : table) {
    std::cout << "PID: " << it.first.pid << " (" << it.first.name << ") "
              << "made " << it.second
              << "Sends on following stack: " << std::endl;
    std::cout << "  User Stack:" << std::endl;
    if (it.first.user_stack >= 0) {
      auto syms = stacks.get_stack_symbol(it.first.user_stack, it.first.pid);
      std::cout <<" Stack Id:"<< it.first.user_stack << std::endl;
      auto addrs = stacks.get_stack_addr(it.first.user_stack);
      for (auto addr : addrs)
        std::cout << "addr->" << addr << std::endl;

       for (auto sym : syms)
        std::cout << "    " << sym << std::endl;
    } else
      std::cout << "    " << it.first.user_stack << std::endl;
  }

  return 0;
}



and the user code to profile. 
// g++ -g -std=c++11 -o send send.cc

#include <iostream>
#include <memory>
#include <chrono>
#include <thread>
#include <vector>
#include <map>
using namespace std;

void* send()
{
    cout<<"called the sent function"<<endl;
    return 0;
}

int main(int argc, char** argv)
{
    send();
    return 0;
}

**Comment by palmtenor** [comment] 2018-04-26 00:54
The target Process need to be alive when doing symbol resolution. That is, we only collect samples and symbolize after `probe_time`, the target process need to be still running at that time, otherwise there is no way to resolve both the memory mapping and the symbol name itself.

**Comment by Eric-Marnadi** [comment] 2018-04-26 00:58
@palmtenor  - thanks  for the info, that was missing piece from my side. The symbols are getting resolved .

**Closed** 2018-04-26 00:59 UTC

**Comment by CR-RanShemesh** [comment] 2022-12-06 15:51
Hi,
I'm also getting prog tag mismatch c02d9a2f664b6371 1 when using bcc 0.20.0 over Ubuntu 20.04.
The program runs after showing this message.

Can you please share your findings regrading the cause of this?
