### ISSUE TITLE
undefined symbol error

### ISSUE THREAD

**Issue by monadbobo** [iovisor/bcc#311] opened 2016-01-12 07:16 UTC
Hello, when using  bcc run the example script, the script report the error:

OSError: /lib64/libbcc.so: undefined symbol: _ZN4llvm20SectionMemoryManager14finalizeMemoryEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

My os is fedora 23, kernel is 4.2.8, llvm/clang is 3.7.1, bcc was compiled by git master(the newest commit).

**Comment by drzaeus77** [comment] 2016-01-12 16:41
Hi, someone else saw this on fedora 23, and I believe the reason is that bcc is being compiled with clang and linked against an llvm library that was itself compiled with gcc. Either that or the gcc version used to compile llvm (from llvm.org/releases) is different than the one used to compile bcc.

So, question 1: did you install clang+llvm from binaries from llvm.org/releases or from source.
Question 2: did you compile bcc with clang or gcc?

Either way, can you try to instead compile clang+llvm from source, and also compile bcc using gcc rather than using the [optional] step that mentions using clang to compile bcc?

**Comment by monadbobo** [comment] 2016-01-12 16:54
Thank you for your reply.

I install clang+lvvm from binaries for llvm.org/releases and I use clang compile bcc.

I will try to use gcc compile bcc.

**Comment by drzaeus77** [comment] 2016-01-12 16:59
I would also compile clang+llvm from source, as you'll note the binary clang releases are only for fedora 22.

**Comment by goldshtn** [comment] 2016-02-04 16:16
I have the same problem on Fedora 23. Using gcc to compile bcc doesn't help -- the same error is produced. 

```
$ sudo /usr/share/bcc/tools/pidpersec 
Traceback (most recent call last):
  File "/usr/share/bcc/tools/pidpersec", line 16, in <module>
    from bcc import BPF
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 29, in <module>
    lib = ct.CDLL("libbcc.so.0")
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libbcc.so.0: undefined symbol: _ZN4llvm20SectionMemoryManager14finalizeMemoryEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

Will try Fedora 22 and report back.

**Comment by drzaeus77** [comment] 2016-02-04 16:24
I think the problem is not using gcc to compile gcc, it is that an older gcc is used to compile the clang+llvm binaries on llvm.org. So, if you recompile clang+llvm using the Fedora 23 gcc, it should work.

**Comment by goldshtn** [comment] 2016-02-04 16:28
It just seems easier and faster to switch to Fedora 22 if that's going to work with the binary LLVM release than to compile Clang+LLVM from source :smiling_imp:

**Comment by drzaeus77** [comment] 2016-02-04 16:37
There is also this: http://rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/c/clang-3.7.1-2.fc24.x86_64.html

Might work on F23?

**Comment by drzaeus77** [comment] 2016-02-04 16:38
Or this: http://rpmfind.net/linux/RPM/fedora/updates/23/x86_64/c/clang-3.7.0-4.fc23.x86_64.html

But that does miss a few BPF fixes for complex programs. Not sure why there wouldn't be a 3.7.1 for fc23.

**Comment by goldshtn** [comment] 2016-02-04 16:49
I'm getting the same error after installing the clang-3.7.0-4.fc23 package and building bcc with clang.

**Comment by drzaeus77** [comment] 2016-02-04 16:56
Can you try building bcc with gcc instead of clang?

**Comment by goldshtn** [comment] 2016-02-04 17:00
Yes, I tried building bcc with gcc instead of clang. That's what I referred to in my [previous comment](https://github.com/iovisor/bcc/issues/311#issuecomment-1799248890). It produced the same error message when trying to run a script.

**Comment by drzaeus77** [comment] 2016-02-04 17:03
Sorry, I didn't mean to ask you to repeat the work. I wasn't sure if that was tried after switching to the .fc23 rpm install of the clang libraries.

**Comment by goldshtn** [comment] 2016-02-04 17:11
No, the error is all mine. I didn't realize you wanted me to try compiling with gcc after switching to the FC23 Clang RPM. But I just tried it and it didn't help either.

**Comment by goldshtn** [comment] 2016-02-04 17:23
In the meantime, I can confirm that everything works fine on Fedora 22 when compiling with Clang+LLVM from the binary releases.

**Comment by goldshtn** [comment] 2016-02-04 17:27
Also, the Clang trunk build finally finished. After building bcc with clang, I get a slightly different undefined symbol error:

```
$ sudo /usr/share/bcc/tools/pidpersec 
Traceback (most recent call last):
  File "/usr/share/bcc/tools/pidpersec", line 16, in <module>
    from bcc import BPF
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 29, in <module>
    lib = ct.CDLL("libbcc.so.0")
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libbcc.so.0: undefined symbol: _ZN5clang8QualType11getAsStringEPKNS_4TypeENS_10QualifiersE
```

**Comment by drzaeus77** [comment] 2016-02-04 17:30
Can you stick with compiling bcc with gcc? I'm fairly confident that clang3.7 won't be able to link against a version of itself that was compiled with gcc 5.3. Go figure. Meanwhile, I'm trying to cook up a set of steps that will use the 3.7.0 fc23 RPMs. I think it should work.

**Comment by goldshtn** [comment] 2016-02-04 17:30
Right, well, I just compiled bcc with gcc and got the same error from the original post. 

```
$ sudo /usr/share/bcc/tools/pidpersec 
Traceback (most recent call last):
  File "/usr/share/bcc/tools/pidpersec", line 16, in <module>
    from bcc import BPF
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 29, in <module>
    lib = ct.CDLL("libbcc.so.0")
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libbcc.so.0: undefined symbol: _ZN4llvm20SectionMemoryManager14finalizeMemoryEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by goldshtn** [comment] 2016-02-04 17:35
Yes, just tried it and getting the same error as in the original post:

```
$ sudo /usr/share/bcc/tools/pidpersec
Traceback (most recent call last):
  File "/usr/share/bcc/tools/pidpersec", line 16, in <module>
    from bcc import BPF
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 29, in <module>
    lib = ct.CDLL("libbcc.so.0")
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libbcc.so.0: undefined symbol: _ZN4llvm20SectionMemoryManager14finalizeMemoryEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by drzaeus77** [comment] 2016-02-04 21:25
I just finished the clang build from source on fc23. I used branch release_37 for llvm and tools/clang. I otherwise followed the instructions at the bottom of INSTALL.md. There was no other clang or llvm rpm installed on the system. I wasn't able to get it working with the fc23 rpm version of clang+llvm. Something is wrong with the cmake files that they are shipping.

**Comment by 4ast** [comment] 2016-02-04 22:48
we've been bitten too many times by cmake version differences and llvm.cmake install problems. I'm cleaning a patch that will use llvm_expand_dependencies() on libraries directly to avoid this pain.

**Comment by goldshtn** [comment] 2017-03-29 11:06
Closing as this is fairly ancient history at this point. Haven't run into problems on FC24/25 with binary clang as of late.

**Closed by goldshtn** 2017-03-29 11:06 UTC
