### ISSUE TITLE
undefined symbol: bpf_module_rw_engine_enabled

### ISSUE THREAD

**Issue by lucky0218** [iovisor/bcc#4542] opened 2023-03-29 15:53 UTC

**Comment by lucky0218** [comment] 2023-03-29 15:54
an error occurred when 'from bcc import BPF' in python

**Comment by arjuntemura** [comment] 2023-06-16 05:15
I encountered the same error with Ubuntu 18.04 and python 3.8. 
How can we resolve this?

**Comment by ShawnZhong** [comment] 2023-08-03 13:47
It works for my by reinstalling BCC: `sudo make install` under `build`

**Comment by matthew-olson-intel** [comment] 2023-10-10 17:28
This issue is caused by trying to use `/usr/lib/x86_64-linux-gnu/libbcc.so` provided by the Ubuntu 18.04 package (which, I think, is `libbpfcc`, if I remember correctly).

The fix here is to use *either* the Ubuntu packages (e.g. `libbpfcc`, `bpfcc-tools`, `libbpfcc-dev`, etc.), *or* the from-source BCC version (so, `sudo make install` after uninstalling the Ubuntu packages).

**Comment by brendangregg** [comment] 2023-10-11 00:10
Thanks @matthew-olson-intel for checking, closing.

**Closed by brendangregg** 2023-10-11 00:10 UTC
