### ISSUE TITLE
 bpftrace - arithmetic on a pointer to an incomplete type 'unsigned long []'

### ISSUE THREAD

**Issue by FrancescoCiraolo** [iovisor/bcc#3556] opened 2021-07-30 19:00 UTC
Hi,
I want to premise this is my first issue submission so, please, feel free to correct the way I'm doing it 
one year ago, for my bachelor thesis, I made a tool to extract the topology information of a running system and the code is using bpftrace, with two different requests.
The point is that now the same requests are no working anymore, both with the same exception "arithmetic on a pointer to an incomplete type 'unsigned long []'"

```
# /usr/sbin/trace-bpfcc -I 'linux-5.11/include/linux/sched/topology.h' 'load_balance(int this_cpu, struct rq *this_rq, struct sched_domain *sd) "[cpu=%d][name=%s][address=%lu][child=%lu][parent=%lu][span=%lu][groups=%lu]", this_cpu, sd->name, sd, sd->child, sd->parent, sd->span[0], sd->groups'
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:45:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:46:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:47:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
/virtual/main.c:57:40: error: no member named 'span_w' in 'struct sched_domain'; did you mean 'span'?
        __data.v5 = (unsigned long)sd->span_w[0];
                                       ^~~~~~
                                       span
/media/francesco/Data/Ext/Projects/IdeaProjects/sched-structs-retriever/linux-5.11/include/linux/sched/topology.h:153:16: note: 'span' declared here
        unsigned long span[];
                      ^
3 warnings and 1 error generated.
Failed to compile BPF module <text>
```

```
# /usr/sbin/trace-bpfcc -I 'linux-5.11/kernel/sched/sched.h' 'group_balance_cpu(struct sched_group *sg) "[address=%lu][cpumask=%lu][next=%lu]", sg, sg->cpumask[0], sg->next'
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:45:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:46:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:47:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
3 warnings generated.
/virtual/main.c:57:166: error: arithmetic on a pointer to an incomplete type 'unsigned long []'
        __data.v1 = (unsigned long)({ typeof(unsigned long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)((&sg->cpumask) + (0))); _val; });
                                                                                                                                                      ~~~~~~~~~~~~~~ ^
1 error generated.
Failed to compile BPF module <text>
```

I have to admit I am not using C for a while now, so maybe the solution is pretty clear but I'm too blind....
Thank you
Francesco

**Comment by yonghong-song** [comment] 2021-08-02 06:24
You used an old kernel for a year ago. Now you are using old code with newer kernels and this triggered a few issues:
  - first the warning w.r.t. BUILTIN_BSWAP16 due to kernel header change, this is fixed in latest bcc.
  - second some fields you are used earlier are gone, e.g., sd->span_w, and you need to find whether there is a new field you can use.
  - third for the error "arithmetic on a pointer to an incomplete type", "struct sched_group" is now in kernel/sched/sched.h, which I see you have included, `cpumask` should be a variable length array in old kernel too. Not sure why this failed with new kernel...

**Comment by FrancescoCiraolo** [comment] 2021-08-02 07:14
Thank you for your reply!

> You used an old kernel for a year ago. Now you are using old code with newer kernels and this triggered a few issues:
> 
>     * first the warning w.r.t. BUILTIN_BSWAP16 due to kernel header change, this is fixed in latest bcc.

Just did it, warning gone! I was going to think about it solved the error

> 
>     * second some fields you are used earlier are gone, e.g., sd->span_w, and you need to find whether there is a new field you can use.

It is interesting that I am not asking that field :thinking:; still, using the last version of bcc it disappeared 

> 
>     * third for the error "arithmetic on a pointer to an incomplete type", "struct sched_group" is now in kernel/sched/sched.h, which I see you have included, `cpumask` should be a variable length array in old kernel too. Not sure why this failed with new kernel...

And that's the big one: only its related output remains, no idea how to solve it

**Comment by yonghong-song** [comment] 2021-08-03 16:50
> And that's the big one: only its related output remains, no idea how to solve it

If you have a reproducible test case, I can take a look.

**Comment by FrancescoCiraolo** [comment] 2021-08-03 17:01
Thank you!
This could be my minimal case:

```
/usr/sbin/trace-bpfcc -I /usr/src/linux-headers-$(uname -r)/include/linux/sched/topology.h 'load_balance(int this_cpu, struct rq *this_rq, struct sched_domain *sd) "[span=%lu]", sd->span[0]'
```

The output is
```
/virtual/main.c:58:163: error: arithmetic on a pointer to an incomplete type 'unsigned long []'
        __data.v0 = (unsigned long)({ typeof(unsigned long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)((&sd->span) + (0))); _val; });
                                                                                                                                                      ~~~~~~~~~~~ ^
1 error generated.
Failed to compile BPF module <text>
```

Is it enough?

**Comment by yonghong-song** [comment] 2021-08-05 05:43
Okay, I found the reason, 5.6 is okay, but 5.12 failed. There is a minor difference for struct field definition.
In 5.6,
```
struct sched_domain {
...
        unsigned long span[0];
};
```
In 5.12,
```
struct sched_domain {
...
        unsigned long span[];
}
```

Note the definition of `span` is different for the above two struct for 5.6 and 5.12.

For 5.12 kernel, you can make a minor change as below:
```
/usr/sbin/trace-bpfcc -I /usr/src/linux-headers-$(uname -r)/include/linux/sched/topology.h 'load_balance(int this_cpu, struct rq *this_rq, struct sched_domain *sd) "[span=%lu]", sd->span'
```
and it should work.

The rewriter probably can be improved for this case. For example, if the field is a pointer and is in the last field of the structure, rewriter may do some adjustment to avoid "[]".

**Comment by FrancescoCiraolo** [comment] 2021-08-05 06:31
Well, not exactly...
I have already tried in this way, but the output is not the first cell of the array but the array memory address. I am pretty sure since is the value I'm searching for should be a bit array of cores: in my system its upper bound should be 4095, but (part of) the output is:
```
0       0       swapper/6       load_balance     [span=18446629132885565216]
0       0       swapper/10      load_balance     [span=18446629132885566240]
0       0       swapper/11      load_balance     [span=18446629132885569312]
0       0       swapper/1       load_balance     [span=18446629132885573408]
0       0       swapper/1       load_balance     [span=18446629132885572384]
0       0       swapper/0       load_balance     [span=18446629132885559584]
0       0       swapper/3       load_balance     [span=18446629132885570336]
0       0       swapper/10      load_balance     [span=18446629132885566240]
0       0       swapper/11      load_balance     [span=18446629132885569312]
799     799     acpid           load_balance     [span=18446629132885573408]
799     799     acpid           load_balance     [span=18446629132885572384]
0       0       swapper/3       load_balance     [span=18446629132885570336]
0       0       swapper/6       load_balance     [span=18446629132885565216]
0       0       swapper/11      load_balance     [span=18446629132885569312]
0       0       swapper/1       load_balance     [span=18446629132885573408]
```

**Comment by yonghong-song** [comment] 2021-08-05 06:47
You are right, how about the following
```
/usr/sbin/trace-bpfcc -I /usr/src/linux-headers-$(uname -r)/include/linux/sched/topology.h 'load_balance(int this_cpu, struct rq *this_rq, struct sched_domain *sd) "[span=%lu]", *(sd->span)'
```

**Comment by FrancescoCiraolo** [comment] 2021-08-05 07:29
That looks perfect! Thank you very much!

**Closed** 2021-08-05 07:29 UTC
