### ISSUE TITLE
Unexpected verifier error

### ISSUE THREAD

**Issue by javierhonduco** [iovisor/bcc#1775] opened 2018-05-21 11:01 UTC
Hi!!

I was making a tool which is very similar to `tools/killsnoop.py`, and got a verifier error that I  don't understand.

I managed to get this same error in `killsnoop` just by moving the initialisation of some struct values to the struct declaration:

```diff
diff --git a/tools/killsnoop.py b/tools/killsnoop.py
index 96f8044..94611e1 100755
--- a/tools/killsnoop.py
+++ b/tools/killsnoop.py
@@ -77,7 +77,6 @@ int do_sys_kill(struct pt_regs *ctx, int tpid, int sig)
 
 int do_ret_sys_kill(struct pt_regs *ctx)
 {
-    struct data_t data = {};
     struct val_t *valp;
     u32 pid = bpf_get_current_pid_tgid();
 
@@ -86,10 +85,13 @@ int do_ret_sys_kill(struct pt_regs *ctx)
         // missed entry
         return 0;
     }
+    struct data_t data = {
+        .pid = pid,
+        .tpid = valp->tpid,
+    
+    };
 
     bpf_probe_read(&data.comm, sizeof(data.comm), valp->comm);
-    data.pid = pid;
-    data.tpid = valp->tpid;
     data.ret = PT_REGS_RC(ctx);
     data.sig = valp->sig;
```

The traceback:
<details>

```
bpf: Failed to load program: Permission denied
0: (bf) r6 = r1
1: (85) call bpf_get_current_pid_tgid#14
2: (63) *(u32 *)(r10 -4) = r0
3: (18) r1 = 0xffff93bd47449a00
5: (bf) r2 = r10
6: (07) r2 += -4
7: (85) call bpf_map_lookup_elem#1
8: (bf) r7 = r0
9: (15) if r7 == 0x0 goto pc+35
 R0=map_value(id=0,off=0,ks=4,vs=32,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=32,imm=0) R10=fp0,call_-1
10: (61) r1 = *(u32 *)(r10 -4)
11: (7b) *(u64 *)(r10 -48) = r1
12: (61) r1 = *(u32 *)(r7 +12)
 R0=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=32,imm=0) R10=fp0,call_-1
13: (b7) r2 = 0
14: (63) *(u32 *)(r10 -16) = r2
15: (63) *(u32 *)(r10 -20) = r2
16: (63) *(u32 *)(r10 -24) = r2
17: (63) *(u32 *)(r10 -28) = r2
18: (63) *(u32 *)(r10 -32) = r2
19: (63) *(u32 *)(r10 -36) = r2
20: (63) *(u32 *)(r10 -40) = r1
21: (bf) r3 = r7
22: (07) r3 += 16
23: (bf) r1 = r10
24: (07) r1 += -28
25: (b7) r2 = 16
26: (85) call bpf_probe_read#4
27: (79) r1 = *(u64 *)(r6 +80)
28: (63) *(u32 *)(r10 -32) = r1
29: (61) r1 = *(u32 *)(r7 +8)
 R0=inv(id=0) R1_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=32,imm=0) R10=fp0,call_-1 fp-40=0
30: (63) *(u32 *)(r10 -36) = r1
31: (18) r2 = 0xffff93bd04792100
33: (bf) r4 = r10
34: (07) r4 += -48
35: (bf) r1 = r6
36: (18) r3 = 0xffffffff
38: (b7) r5 = 40
39: (85) call bpf_perf_event_output#25
invalid indirect read from stack off -48+36 size 40

Traceback (most recent call last):
  File "../tools/killsnoop.py", line 118, in <module>
[...]
```

</details>

While trying to understand this, I reduced it to this script:
<details>

```python3
#!/usr/bin/python3 
from __future__ import print_function 
from bcc import BPF 
import argparse 
from time import strftime 
import ctypes as ct 
 
# define BPF program
bpf_text = """

struct data_t {
   u64 pid;
   int sig;
};

BPF_PERF_OUTPUT(events);

int do_ret_sys_kill(struct pt_regs *ctx)
{
    struct data_t valp = {
        .sig = 0,
    };

    struct data_t data = {
        .sig = valp.sig,
    };

    events.perf_submit(ctx, &data, sizeof(data));

    return 0;
}
"""
b = BPF(text=bpf_text)
b.attach_kretprobe(
    event=b.get_syscall_fnname("kill"),
    fn_name="do_ret_sys_kill",
)
```

</details>

#### Observations
I've managed to make the verifier happy by:
- Initialising struct members not where the struct is being declared
- Adding some new element to the struct (like another `int`)
- Removing the call to `bpf_perf_event_output`

I checked the disassembly of the eBPF code generated by the program above (passing `debug=8` to `BCC()`), first as-is, and the second time adding an extra `u64` field to the struct, and couldn't see anything weird:
```diff
$ diff ok.txt fail.txt 
6c6
<    1:	7b 2a f8 ff 00 00 00 00 	*(u64 *)(r10 - 8) = r2
---
>    1:	63 2a f8 ff 00 00 00 00 	*(u32 *)(r10 - 8) = r2
```
 
#### Conclusion
My knowledge here is pretty limited and I couldn't find out the root cause :cry:. However, it sounds like it could either be something related to memory alignment / struct packing? 

Sorry I didn't manage to provide more information and thanks! :smile:

**Comment by pchaigno** [comment] 2018-05-21 13:41
This is a duplicate of #269. The issue was also reported in #382 and #446, the issue being that, because the `data_t` structure has padding for alignment, it requires special care for the initialization. Meaning its padding needs to be zeroed out. This happens (can be seen in the generated BPF bytecode) when initializing with `{}`. When initializing using designated initializers, however, the padding is not zeroed out.

**Comment by javierhonduco** [comment] 2018-05-21 16:02
Thanks for the explanation, Paul, and sorry I didn’t see this was a duplicated issue

**Closed** 2018-07-19 00:33 UTC
