### ISSUE TITLE
Fail to tail a eBPF program

### ISSUE THREAD

**Issue by zwendi** [iovisor/bcc#4642] opened 2023-06-16 21:18 UTC
Ebpf program:
```
#include <linux/cred.h>
#include <linux/dcache.h>
#include <linux/fdtable.h>
#include <linux/fs_struct.h>
#include <linux/limits.h>
#include <linux/magic.h>
#include <linux/mm.h>
#include <linux/mount.h>
#include <linux/sched.h>
#include <linux/version.h>
#include <uapi/linux/fcntl.h>
#include <uapi/linux/ptrace.h>
#include <uapi/linux/mman.h>

BPF_PROG_ARRAY(prog_array, 10);

int tail_call(void *ctx) {
    bpf_trace_printk("Tail-call\n");
    return 0;
}

int do_tail_call(void *ctx) {
    bpf_trace_printk("Original program\n");
    prog_array.call(ctx, 2);
    return 0;
}
 
```
when calling `BPF::init` with above program and empty `cflags`, the initialization will fail and have the following error is standard out:
```
1 warning generated.
/virtual/main.c:44:20: error: incompatible pointer to integer conversion passing 'void *' to parameter of type 'u64' (aka 'unsigned long long') [-Wint-conversion]
    bpf_tail_call_((void *)bpf_pseudo_fd(1, -1), ctx, 0);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/virtual/include/bcc/helpers.h:552:25: note: passing argument to parameter 'map_fd' here
void bpf_tail_call_(u64 map_fd, void *ctx, int index) {
```

BCC version: 0.26.0
kernel: 5.15.49-linuxkit

**Comment by yonghong-song** [comment] 2023-06-20 15:27
The issue should have been fixed with commit:
  https://github.com/iovisor/bcc/commit/7a90c7b232a002f276dacaecc9c714dab75f68ab
which is in 0.26.0. could you check latest source to see whether the issue is gone or not?

**Comment by zwendi** [comment] 2023-06-20 15:33
@yonghong-song  It seems like my issue is caused by explicitly casting the fd to a `(void *)` and `bpf_tail_call_` is expecting a  `u64` ?

**Comment by zwendi** [comment] 2023-06-20 16:02
Do you have estimate on when the fix will be available in a newer release? I will close the issue. Thanks.

**Closed** 2023-06-20 16:03 UTC
