### ISSUE TITLE
src/python/bcc/version.py created as part of build

### ISSUE THREAD

**Issue by bolinfest** [iovisor/bcc#1964] opened 2018-09-10 06:33 UTC
I'm on Ubuntu 18.04.1. First, note that the build instructions:

```
# Trusty and older
VER=trusty
echo "deb http://llvm.org/apt/$VER/ llvm-toolchain-$VER-3.7 main
deb-src http://llvm.org/apt/$VER/ llvm-toolchain-$VER-3.7 main" | \
  sudo tee /etc/apt/sources.list.d/llvm.list
wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
sudo apt-get update

# All versions
sudo apt-get -y install bison build-essential cmake flex git libedit-dev \
  libllvm3.7 llvm-3.7-dev libclang-3.7-dev python zlib1g-dev libelf-dev

# For Lua support
sudo apt-get -y install luajit luajit-5.1-dev
```

mention Trusty (14.04) and older, so I wasn't sure what to do for 18.04. I ended up copypasta'ing some stuff from the [LLVM Debian/Ubuntu nightly packages](http://apt.llvm.org/) and created `/etc/apt/sources.list.d/llvm.list` with the following contents:

```
# i386 not available
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
# 6.0
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main
# 7
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main
```

Then I basically followed the existing instructions, but instead of:

```
sudo apt-get -y install libllvm3.7 llvm-3.7-dev libclang-3.7-dev
```

I did:

```
sudo apt-get -y install libllvm7 llvm7-dev libclang-7-dev
```

(Note that I originally tried this with `8` instead of `7`, but then building bcc failed because the [`getLocStart()` API appears to have been renamed in LLVM 8](http://clang-developers.42468.n3.nabble.com/API-Removal-Notice-4-weeks-getStartLoc-getLocStart-getLocEnd-td4061566.html).)

Now the problem was getting things to build because everything seems hardcoded for LLVM 3.7. I rooted around in `CMakeLists.txt` and found `$LLVM_LIBRARY_DIRS`, so adding an extra argument to `cmake` worked fine:

```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_LIBRARY_DIRS=/usr/lib/llvm-7/lib
```

However, when I was done, `git status` was not clean, as there was the file `src/python/bcc/version.py` with the following contents:

```
__version__ = '0.7.0-8cc0bda6'
```

Not a huge deal, but it would be nice if this file were either not created, created under `build/`, or listed in `.gitignore`.

It would also be nice if the Ubuntu build instructions were updated to call out what to do for versions after Trusty. Hopefully the record of the steps I went through (and the upcoming breaking in LLVM 8) are useful here.

**Comment by yonghong-song** [comment] 2018-09-10 16:41
Yes, this can be easily reproduced. Somehow, when I change branch and did a rebuild. This `src/python/bcc/version.py` will show up. I do not know why either.

**Comment by pchaigno** [comment] 2018-09-10 16:46
I noticed that as well, but didn't took the time to debug it. I think it's been happening since #1826 got merged.

**Comment by yonghong-song** [comment] 2018-09-10 16:51
@pchaigno Yes, #1826 introduced a version.py in the source tree to generate a version.py at build the directory.

**Comment by pchaigno** [comment] 2018-09-10 17:07
Looks like adding that file to `.gitignore` would be the right fix here since it's generated at build time from `version.py.in`...?

**Comment by bolinfest** [comment] 2018-09-10 19:33
@pchaigno Adding it to `.gitignore` would certainly be the quickest fix, though it always seems a bit dirty to me to have generated code in the `src/` folder as opposed to the `build/` folder, but maybe it's not worth the effort to move it?

**Comment by pchaigno** [comment] 2018-09-10 19:59
@bolinfest Right, it probably would be best to generate that file in `build/`. @andihit Was this the intended behavior? Would it be possible to generate `version.py` in the build directory only?

**Comment by yonghong-song** [comment] 2018-09-10 20:03
We could add an entry in `.gitignore`. But looking at the source code, I don't understand why this can happen? Any idea?

**Comment by brendangregg** [comment] 2018-09-12 16:34
this issue is annoying my builds as well...

**Comment by andihit** [comment] 2018-09-12 17:04
@pchaigno Basically I followed the same approach as it's used for creating `setup.py` from `setup.py.in` (https://github.com/iovisor/bcc/blob/master/src/python/CMakeLists.txt#L14)

Yes, `build/` directory would be fine also.
Any idea why the `setup.py` is cleaned after the build but `bcc/version.py` is not?

I'll see if I get time in a few days, probably we just need another directory insead of `${CMAKE_CURRENT_BINARY_DIR}` in the cmake file.

**Comment by mauriciovasquezbernal** [comment] 2018-09-25 23:03
@andihit you are actually generating `version.py` in the `build/` folder, but there is a link between the `build/src/python/bcc` and the `src/python/bcc` folders -> https://github.com/iovisor/bcc/blob/master/src/python/CMakeLists.txt#L8.

I think just adding `version.py` to `.gitignore` will solve those issues.

**Comment by yonghong-song** [comment] 2018-09-26 04:45
Sounds good then, could you submit a pull request for this? Could you double check when we do a make clean, we do clean this file as well? Thanks!

**Comment by mauriciovasquezbernal** [comment] 2018-10-04 18:22
I think this can be close after https://github.com/iovisor/bcc/pull/1989.

**Comment by yonghong-song** [comment] 2018-10-05 02:00
Just closed the issue!

**Closed** 2018-10-05 01:59 UTC
