### ISSUE TITLE
Planned Support for Hash of Maps?

### ISSUE THREAD

**Issue by HousedHorse** [iovisor/bcc#2347] opened 2019-05-11 02:10 UTC
I was looking at [table.py](https://github.com/iovisor/bcc/blob/master/src/python/bcc/table.py) and noticed there seems to be a map_type_name defined for HASH_OF_MAPS and ARRAY_OF_MAPS.

```python
map_type_name = {BPF_MAP_TYPE_HASH: "HASH",
                 ...
                 BPF_MAP_TYPE_ARRAY_OF_MAPS: "ARRAY_OF_MAPS",
                 BPF_MAP_TYPE_HASH_OF_MAPS: "HASH_OF_MAPS",
                 ...
BPF_MAP_TYPE_SOCKHASH: "SOCKHASH",}
```

Presumably this implies the possibility of nested hashmaps? Is this a planned feature for a future release?

**Comment by palmtenor** [comment] 2019-05-13 15:42
Yes, but the trick is in order to support map-of-maps we'll need some sort of two-pass compilation, first pass to create the inner map and use that fd to create outer map. I have had some ideas and worked out some code a while ago, let me try to find them...

**Comment by HousedHorse** [comment] 2019-05-13 16:49
> Yes, but the trick is in order to support map-of-maps we'll need some sort of two-pass compilation, first pass to create the inner map and use that fd to create outer map. I have had some ideas and worked out some code a while ago, let me try to find them...

Thank you so much. If you could find your old code that would be much appreciated.

**Comment by palmtenor** [comment] 2019-05-13 17:09
I think we should just support this. I will try put them together and send out an RFC

**Comment by yonghong-song** [comment] 2019-05-17 05:52
thanks @palmtenor!

**Comment by HousedHorse** [comment] 2019-05-30 15:56
@palmtenor Any news on this?

**Comment by palmtenor** [comment] 2019-07-02 19:31
Duplicate of #1318

**Closed by palmtenor** 2019-07-02 19:31 UTC
