### ISSUE TITLE
USDT: !read_ok

### ISSUE THREAD

**Issue by jesperpedersen** [iovisor/bcc#1112] opened 2017-04-13 15:42 UTC
I have an USDT defined as
```
  location #1 0x808d43
    argument #1 8 unsigned bytes @ ax                                                                                                                                                                    
    argument #2 4 unsigned bytes @ *(bp - 44)                                                                                                                                                            
  location #2 0x809266                                                                                                                                                                                   
    argument #1 8 unsigned bytes @ ax                                                                                                                                                                    
    argument #2 4 signed   bytes @ 0
```

when executed gives

```
bpf: Permission denied
0: (bf) r1 = r10
1: (07) r1 += -4
2: (b7) r2 = 4
3: (85) call bpf_probe_read#4
R3 !read_ok

Traceback (most recent call last):
  File "./postgresql_locks", line 63, in <module>
    b = BPF(text=bpf_text, usdt_contexts=[u])
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 296, in __init__
    usdt_context.attach_uprobes(self)
  File "/usr/lib/python2.7/site-packages/bcc/usdt.py", line 181, in attach_uprobes
    addr=addr, pid=pid)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 818, in attach_uprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 344, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program do_acquire: Permission denied
```

If I change its definition to
```
  location #1 0x808d43                                                                                                                                                                                   
    argument #1 8 unsigned bytes @ ax                                                                                                                                                                    
    argument #2 4 unsigned bytes @ *(bp - 44)                                                                                                                                                            
  location #2 0x809266                                                                                                                                                                                   
    argument #1 8 unsigned bytes @ ax                                                                                                                                                                    
    argument #2 4 unsigned bytes @ 0
```

I still get
```
bpf: Permission denied                                                                                                                                                                                   
0: (bf) r1 = r10
1: (07) r1 += -4
2: (b7) r2 = 4
3: (85) call bpf_probe_read#4
R3 !read_ok

Traceback (most recent call last):
  File "./postgresql_locks", line 63, in <module>
    b = BPF(text=bpf_text, usdt_contexts=[u])
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 296, in __init__
    usdt_context.attach_uprobes(self)
  File "/usr/lib/python2.7/site-packages/bcc/usdt.py", line 181, in attach_uprobes
    addr=addr, pid=pid)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 818, in attach_uprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 344, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program do_acquire: Permission denied
```

The code used is
```
    uint64_t addr;
    unsigned int val;

    bpf_usdt_readarg(2, ctx, &addr);
    bpf_probe_read(&val, sizeof(val), (void *)addr);

    bpf_trace_printk("Value: %d\\n", val);

    return 0;
```

Argument 2 is an enum, and location 2 is a call site with a constant from the enum

I have other USDTs working, just not this one. Is it a question of unsigned vs. signed in the first case, or a matter of using a constant in location 2 ?

Thanks in advance for any help on this !

**Comment by goldshtn** [comment] 2017-04-13 16:15
Interesting. Can you print the full BPF program please, including the USDT expansions? You can get the text from the USDT object's get_text method.

**Comment by jesperpedersen** [comment] 2017-04-13 19:04
USDT:
```
#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_do_acquire_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  switch(ctx->ip) {
  case 0x808d43ULL: *((uint64_t *)dest) = (uint64_t)ctx->ax; return 0;
  case 0x809266ULL: *((uint64_t *)dest) = (uint64_t)ctx->ax; return 0;
  }
  return -1;
}
static inline int _bpf_readarg_do_acquire_2(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint32_t)) return -1;
  switch(ctx->ip) {
  case 0x808d43ULL: { u64 __addr = ctx->bp + (-44);uint32_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint32_t *)dest) = __res; } return 0;
  case 0x809266ULL: *((uint32_t *)dest) = 0; return 0;
  }
  return -1;
}
```

Source:
```
#!/usr/bin/python
#
# postgresql_locks  Analyze PostgreSQL LWLock usage
#                   For Linux, uses BCC, BPF. Embedded C.
#
# USAGE: postgresql_locks
#
# Copyright 2017 Red Hat
# Licensed under the Apache License, Version 2.0 (the "License")

from __future__ import print_function
from bcc import BPF, USDT
import sys
import subprocess

if len(sys.argv) < 1:
    print("USAGE: postgresql_locks <pid>")
    exit()

# load BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>

int do_acquire(struct pt_regs *ctx) {
    uint64_t m_addr;
    unsigned int mode;

    bpf_usdt_readarg(2, ctx, &m_addr);
    bpf_probe_read(&mode, sizeof(mode), (void *)m_addr);

    bpf_trace_printk("Acquire: %d\\n", mode);

    return 0;
};
"""

# Bug https://github.com/iovisor/bcc/issues/1106
# pids = map(int, subprocess.check_output("pidof postgres".split()).split())
# usdts = map(lambda pid: USDT(pid=pid), pids)
# for usdt in usdts:
#     usdt.enable_probe_or_bail("lwlock__acquire", "do_acquire")

# initialize USDT and BPF
u = USDT(pid=int(sys.argv[1]))
u.enable_probe_or_bail(probe="lwlock__acquire", fn_name="do_acquire")

print("USDT")
print(u.get_text())
print("BPF")
print(bpf_text)

b = BPF(text=bpf_text, usdt_contexts=[u])

# header
print("%-18s %-16s %-6s %s" % ("TIME", "COMM", "PID", "LOCK"))

# format output
while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        print("value error")
        continue
    print("%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))
```

**Comment by goldshtn** [comment] 2017-04-13 19:24
Right, so two locations accessing different registers. @4ast Could this be the same issue as https://github.com/iovisor/bcc/issues/751?

**Comment by goldshtn** [comment] 2017-04-14 17:45
Looked at this some more, and reproduced on my own box. It seems that this is caused by the fact your `m_addr` variable is declared as a 64-bit integer, whereas the 2nd location of your probe is a 32-bit integer. As a result, I suspect `bpf_probe_read` considers the `(void *)m_addr` to be a partially uninitialized expression.

I don't know why you'd expect the 32-bit integer to contain a memory address, but in any case after changing `m_addr` to u32, the program builds and loads (with a warning).

@jesperpedersen

**Comment by jesperpedersen** [comment] 2017-04-17 16:35
Well, it depends on the contract between `bpf_usdt_readarg` and `bpf_probe_read`.

In the `_bpf_readarg_do_acquire_1` case `dest` will contain the memory address to the value, and hence `bpf_probe_read` is needed. However, in the `_bpf_readarg_do_acquire_2` case `dest` will contain the value, and no `bpf_probe_read` call is needed.

The reference guide doesn't specify if the above is correct, but the generated code does indicate that - I agree with you there.

(Adding in the readarg(1) to the `const char *` does cause another crash, but that is a separate issue)

**Comment by goldshtn** [comment] 2017-04-17 16:40
Not sure if I understood you 100%, but in any case the design of the USDT helpers is such that we get you the actual value, even if it's on the stack or in a global and we need a bpf_probe_read to fetch it. That's what the generated code does. If the documentation is unclear on this, we can fix the part that is confusing. 

Are you saying that you have another crash due to the USDT code? Or unrelated?

**Comment by jesperpedersen** [comment] 2017-04-17 16:48
I meant in `_bpf_readarg_do_acquire_2` the call to `bpf_probe_read` is done in the generated code, and therefore I don't need to call it in my function.

Source:
```
#!/usr/bin/python
#
# postgresql_locks  Analyze PostgreSQL LWLock usage
#                   For Linux, uses BCC, BPF. Embedded C.
#
# USAGE: postgresql_locks <pid>
#
# Copyright 2017 Red Hat
# Licensed under the Apache License, Version 2.0 (the "License")

from __future__ import print_function
from bcc import BPF, USDT
import sys
import subprocess

if len(sys.argv) < 1:
    print("USAGE: postgresql_locks <pid>")
    exit()

debug=1

# load BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>

int do_acquire(struct pt_regs *ctx) {
    uint64_t n_addr;
    char name[256];
    unsigned int mode;

    bpf_usdt_readarg(1, ctx, &n_addr);
    bpf_usdt_readarg(2, ctx, &mode);

    bpf_probe_read(&name, sizeof(name), (void *)n_addr);

    bpf_trace_printk("Acquire: %s %d\\n", name, mode);

    return 0;
};
"""

# Bug https://github.com/iovisor/bcc/issues/1106
# pids = map(int, subprocess.check_output("pidof postgres".split()).split())
# usdts = map(lambda pid: USDT(pid=pid), pids)
# for usdt in usdts:
#     usdt.enable_probe_or_bail("lwlock__acquire", "do_acquire")

# initialize USDT and BPF
u = USDT(pid=int(sys.argv[1]))
u.enable_probe_or_bail(probe="lwlock__acquire", fn_name="do_acquire")

if debug:
    print("USDT")
    print(u.get_text())
    print("BPF")
    print(bpf_text)

b = BPF(text=bpf_text, usdt_contexts=[u])

# header
print("%-18s %-16s %-6s %s" % ("TIME", "COMM", "PID", "LOCK"))

# format output
while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        print("value error")
        continue
    print("%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))
```

gives

```
USDT
#include <uapi/linux/ptrace.h>
static inline int _bpf_readarg_do_acquire_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  switch(ctx->ip) {
  case 0x808d43ULL: *((uint64_t *)dest) = (uint64_t)ctx->ax; return 0;
  case 0x809266ULL: *((uint64_t *)dest) = (uint64_t)ctx->ax; return 0;
  }
  return -1;
}
static inline int _bpf_readarg_do_acquire_2(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint32_t)) return -1;
  switch(ctx->ip) {
  case 0x808d43ULL: { u64 __addr = ctx->bp + (-44);uint32_t __res = 0x0; bpf_probe_read(&__res, sizeof(__res), (void *)__addr); *((uint32_t *)dest) = __res; } return 0;
  case 0x809266ULL: *((uint32_t *)dest) = 0; return 0;
  }
  return -1;
}

BPF

#include <uapi/linux/ptrace.h>

int do_acquire(struct pt_regs *ctx) {
    uint64_t n_addr;
    char name[256];
    unsigned int mode;

    bpf_usdt_readarg(1, ctx, &n_addr);
    bpf_usdt_readarg(2, ctx, &mode);

    bpf_probe_read(&name, sizeof(name), (void *)n_addr);

    bpf_trace_printk("Acquire: %s %d\n", name, mode);

    return 0;
};

bpf: Permission denied
0: (79) r2 = *(u64 *)(r1 +128)
1: (15) if r2 == 0x809266 goto pc+1
 R1=ctx R2=inv R10=fp
2: (55) if r2 != 0x808d43 goto pc+1
 R1=ctx R2=inv,min_value=8424771,max_value=8424771 R10=fp
3: (79) r6 = *(u64 *)(r1 +80)
4: (b7) r7 = 0
5: (55) if r2 != 0x808d43 goto pc+9
 R1=ctx R2=inv,min_value=8424771,max_value=8424771 R6=inv R7=imm0,min_value=0,max_value=0 R10=fp
6: (79) r3 = *(u64 *)(r1 +32)
7: (b7) r1 = 0
8: (63) *(u32 *)(r10 -4) = r1
9: (07) r3 += -44
10: (bf) r1 = r10
11: (07) r1 += -4
12: (b7) r2 = 4
13: (85) call bpf_probe_read#4
14: (61) r7 = *(u32 *)(r10 -4)
15: (bf) r8 = r10
16: (07) r8 += -272
17: (bf) r1 = r8
18: (b7) r2 = 256
19: (bf) r3 = r6
20: (85) call bpf_probe_read#4
21: (18) r1 = 0x20732520
23: (7b) *(u64 *)(r10 -280) = r1
24: (18) r1 = 0x75716341
26: (7b) *(u64 *)(r10 -288) = r1
27: (bf) r1 = r10
28: (07) r1 += -288
29: (b7) r2 = 16
30: (bf) r3 = r8
31: (bf) r4 = r7
32: (85) call bpf_trace_printk#6
33: (b7) r0 = 0
34: (95) exit

from 5 to 15: R1=ctx R2=inv,min_value=8424771,max_value=8424771 R6=inv R7=imm0,min_value=0,max_value=0 R10=fp
15: (bf) r8 = r10
16: (07) r8 += -272
17: (bf) r1 = r8
18: (b7) r2 = 256
19: (bf) r3 = r6
20: (85) call bpf_probe_read#4
21: (18) r1 = 0x20732520
23: (7b) *(u64 *)(r10 -280) = r1
24: (18) r1 = 0x75716341
26: (7b) *(u64 *)(r10 -288) = r1
27: (bf) r1 = r10
28: (07) r1 += -288
29: (b7) r2 = 16
30: (bf) r3 = r8
31: (bf) r4 = r7
32: (85) call bpf_trace_printk#6
33: (b7) r0 = 0
34: (95) exit

from 2 to 4: R1=ctx R2=inv R10=fp
4: (b7) r7 = 0
5: (55) if r2 != 0x808d43 goto pc+9
 R1=ctx R2=inv,min_value=8424771,max_value=8424771 R7=imm0,min_value=0,max_value=0 R10=fp
6: (79) r3 = *(u64 *)(r1 +32)
7: (b7) r1 = 0
8: (63) *(u32 *)(r10 -4) = r1
9: (07) r3 += -44
10: (bf) r1 = r10
11: (07) r1 += -4
12: (b7) r2 = 4
13: (85) call bpf_probe_read#4
14: (61) r7 = *(u32 *)(r10 -4)
15: (bf) r8 = r10
16: (07) r8 += -272
17: (bf) r1 = r8
18: (b7) r2 = 256
19: (bf) r3 = r6
R6 !read_ok

Traceback (most recent call last):
  File "./postgresql_locks", line 58, in <module>
    b = BPF(text=bpf_text, usdt_contexts=[u])
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 296, in __init__
    usdt_context.attach_uprobes(self)
  File "/usr/lib/python2.7/site-packages/bcc/usdt.py", line 181, in attach_uprobes
    addr=addr, pid=pid)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 818, in attach_uprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 344, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program do_acquire: Permission denied
```

**Comment by goldshtn** [comment] 2017-04-17 18:24
You need to initialize `n_addr` (e.g. to 0), because it might not be initialized before passing it to `bpf_probe_read`. The reason is basically that the readarg helper is not guaranteed to initialize the output parameter. This is probably something we could improve upon -- either in the docs, or in the generated helper.

**Comment by jesperpedersen** [comment] 2017-04-18 13:08
Yeah, updating the documentation around `bpf_usdt_readarg` with its requirements, and when you should call `bpf_probe_read` explicit should be enough

**Comment by goldshtn** [comment] 2017-04-18 15:11
If you feel like tackling this, a PR would be very welcome! Especially from the point of view of someone actually reading the documentation to figure it out, and not someone documenting the code they wrote :)

**Comment by jesperpedersen** [comment] 2017-04-18 15:37
Sounds good, I'll try and type something up

**Comment by goldshtn** [comment] 2017-04-18 19:20
Cool. Closing for now.

**Closed by goldshtn** 2017-04-18 19:20 UTC

**Comment by jesup** [comment] 2018-08-24 13:39
@goldshtn @jesperpedersen 
Was there any update to the docs here?  I got bitten by this trying to modify one of the examples into something that would export a string passed to DTRACE_PROBEn -- and spent a ton of time poking around with my macros that inserted the probes until I found this.

My program is now:
`struct data_t {
   u32 pid;
   char label[64];
   u64 ts;
   u32 category;
};
BPF_PERF_OUTPUT(events);

int do_trace(struct pt_regs *ctx) {
    struct data_t data = {};
    uint64_t addr;
    addr = 0;
    data.pid = bpf_get_current_pid_tgid();
    data.ts = bpf_ktime_get_ns();
    bpf_usdt_readarg(1, ctx, &addr);
    if (addr == 0) {
      return 0;
    } 
    bpf_probe_read(&data.label, sizeof(data.label), (void *)addr);
    bpf_usdt_readarg(2, ctx, &data.category);
    events.perf_submit(ctx, &data, sizeof(data));

    return 0;
};
`
The fix was to add 'addr = 0;' as above (though perhaps I should be checking readarg's result instead - though why would it fail?).  Before that, if I manually inserted a single probe, it worked, but if my addition to an existing trace macro in Firefox caused a handful of probes to be created, I'd get this error.

If users are expected to always test bpf_usdt_readarg()'s result, the examples should do that, or have a comment saying why it's not needed in that case. (I get there's limited program space and often these are perf-sensitive to run, so avoiding unneeded checks will be tempting.)

**Comment by jesup** [comment] 2018-08-24 13:50
And perhaps more to the point, why would it fail here?  Every instance with that probe has that argument and it's a string.... (there are only about 14 in this case):
```
gecko_label:NETWORK [sema 0x0]
  location #1 ./libxul.so 0x99676c
    argument #1 8 unsigned bytes @ dx
    argument #2 4 unsigned bytes @ 5
  location #2 ./libxul.so 0x99bcfd
    argument #1 8 unsigned bytes @ r15
    argument #2 4 unsigned bytes @ 5
  location #3 ./libxul.so 0x99beb1
    argument #1 8 unsigned bytes @ r14
    argument #2 4 unsigned bytes @ 5
  location #4 ./libxul.so 0x9a17d6
    argument #1 8 unsigned bytes @ r14
    argument #2 4 unsigned bytes @ 5
  location #5 ./libxul.so 0x9a1b91
    argument #1 8 unsigned bytes @ r14
    argument #2 4 unsigned bytes @ 5
  location #6 ./libxul.so 0x9dbfce
    argument #1 8 unsigned bytes @ r15
    argument #2 4 unsigned bytes @ 5
  location #7 ./libxul.so 0xbebbe2
    argument #1 8 unsigned bytes @ cx
    argument #2 4 unsigned bytes @ 5
  location #8 ./libxul.so 0xbf3edb
    argument #1 8 unsigned bytes @ r13
    argument #2 4 unsigned bytes @ 5
  location #9 ./libxul.so 0xbf52ff
    argument #1 8 unsigned bytes @ r15
    argument #2 4 unsigned bytes @ 5
  location #10 ./libxul.so 0x16fbb26
    argument #1 8 unsigned bytes @ dx
    argument #2 4 unsigned bytes @ 5
  location #11 ./libxul.so 0x17022de
    argument #1 8 unsigned bytes @ r15
    argument #2 4 unsigned bytes @ 5
  location #12 ./libxul.so 0x222c520
    argument #1 8 unsigned bytes @ dx
    argument #2 4 unsigned bytes @ 5
  location #13 ./libxul.so 0x28f1866
    argument #1 8 unsigned bytes @ r15
    argument #2 4 unsigned bytes @ 5
  location #14 ./libxul.so 0x28f2ae8
    argument #1 8 unsigned bytes @ dx
    argument #2 4 unsigned bytes @ 5
```

**Comment by yonghong-song** [comment] 2018-08-25 06:09
@jesup do you mind to send a pull request? The fundamental reason is verifier expects the src_addr in bpf_probe_read initialized. There are two ways to achieve this for usdt use cases:
   . initialize that address, or
   . add some checking etc. to ensure the execution going to the bpf_probe_read does have the src_addr assigned. For this, you may need to understand usdt implementation details a little bit.

The first option is easier compared to the second option.
Not sure where to put it?  bcc/FAQ.txt seems a natural fit? doc/reference_guide under somewhere USDT, not sure where.
