### ISSUE TITLE
`biotop` and `biosnoop` do not work under 5.19 kernel due to missing `blk_account_io_start` kprobe

### ISSUE THREAD

**Issue by haozhangphd** [iovisor/bcc#4261] opened 2022-09-30 12:53 UTC
On the latest Arch Linux installation, and Fedora 36 with 5.19 kernel, the kprobes `blk_account_io_start` as well as `__blk_account_io_start` are missing, as seen from the `/proc/kallsyms` file. As a result, both `biotop` and `biosnoop` fail to start with the following error messages:
`Exception: Failed to attach BPF program b'trace_pid_start' to kprobe b'blk_account_io_start', it's not traceable (either non-existing, inlined, or marked as "notrace")
`

**Comment by devidasjadhav** [comment] 2022-10-06 17:07
This is correct but its caused by linux kernel
[450b7879e34517c3ebc3a35a53806fe40e60fac2](https://github.com/torvalds/linux/commit/450b7879e34517c3ebc3a35a53806fe40e60fac2) and its introduced in 5.17 onwards.

Kernel Devs don't guaranty tracing symbols similar to linux ABI.  this is not issue with bcc but linux kernel.

there can be workaround reverting commit mentioned above and compiling kernel manually. 
If not changing `static inline void` to `void` would resolve this.

As this is not related to bcc please close this issue.
If need more clarification do ask for more clarification here.
I will try my best to answer.

**Comment by haozhangphd** [comment] 2022-10-06 18:26
I think bcc needs to be kept up-to-date with respect to the kernel, and not the other way around. Manually reverting kernel commits in order to make bcc work is not practical. 

In the past bcc has always kept pace with the kernel tracing symbol changes, as evidenced by for example 95c9229ea9f029a1b9e8dcbe86fc67f037c0dfa2 and 97c20767923db7ea8c1ec6e07b2297b00992af03. Thus incompatibility with the latest kernel is indeed a bcc issue.

**Comment by haozhangphd** [comment] 2022-10-12 15:33
> I do not know for `biosnoop` but the [CO-RE version of `biotop`](https://github.com/iovisor/bcc/blob/304692d1b48dde37ca1395d721aab3a3e8fdf75c/libbpf-tools/biotop.c#L395-L403) normally handles the case you point.

From the source code, it seems the CO-RE version depends on the same two kprobes `__blk_account_io_start` or `blk_account_io_start` as the python version? On newer kernels without either of these two kprobes, it seems I cannot use the CO-RE version as well...

**Comment by haozhangphd** [comment] 2022-10-12 22:12
I tried manually patching the kernel by making `__blk_account_io_start` noinline, and `biotop` indeed works. However I don't think this is a practical solution for most of the users, as these `bio` functions will be unusable for anyone using kernels newer than 5.17. Is there any other kprobe that can be used besides `__blk_account_io_start` for similar purpose?

**Comment by chenhengqi** [comment] 2022-10-13 12:39
Maybe we can add a tracepoint for it. I am working on it.

**Comment by darkblaze69** [comment] 2022-11-18 06:01
Is there a temporary workaround for this issue? also for newer kernels 6.0 and 6.1rc?

**Comment by yonghong-song** [comment] 2022-11-26 23:45
indeed, tracepoint is the best option here. There might be an alternative to blk_account_to_io_start() but it might produce a different result or that function might be inlined as well. So ultimately, @chenhengqi suggested tracepoint might be the best long term solution. I see one tracepoint block/block_bio_complete, but didn't dig out whether it is an appropriate replacement or not.

**Comment by Rtoax** [comment] 2023-02-15 03:05
Sorry, my mistake, there is a `tracepoint:writeback:writeback_dirty_folio`, i closed PR(https://github.com/iovisor/bcc/pull/4482), and i'll submit a new one.

**Closed** 2023-08-02 16:06 UTC
Labels: bug, good first issue
